name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Install dependencies for Puppeteer and Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl libgtk-3-0 libdbus-1-3 libgdk-pixbuf2.0-0 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 libasound2 libatk-bridge2.0-0 libatk1.0-0 libnspr4 libxtst6 xdg-utils
        # Instalacja Chromium (przeglądarka potrzebna do Puppeteer)
        sudo apt-get install -y chromium-browser

    - name: Run Node.js app with Puppeteer
      run: |
        # Uruchomienie pliku app.js
        node json.js  # Zmień 'app.js' na nazwę swojego pliku Node.js
      env:
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser # Ścieżka do Chromium w systemie Linux
